"""
Command-Line Interface definition for GhostMirror-Py, utilizing the Click library.

This module sets up all command-line options, handles initial configuration processing
(like path expansion), and then passes the configuration to the core processing logic.
"""
import click
# import os # Not strictly used directly
import pathlib
from . import core 

def path_home() -> pathlib.Path:
    """
    Returns the user's home directory as a `pathlib.Path` object.

    This is a simple wrapper around `pathlib.Path.home()` for convenience.

    Returns:
        pathlib.Path: The path to the user's home directory.
    """
    return pathlib.Path.home()

def path_explode(path_str: str | None) -> str | None:
    """
    Expands and resolves a path string.

    Handles common path idioms:
    - If `path_str` is None or empty, returns None.
    - If `path_str` starts with "~/", it expands "~" to the user's home directory.
    - Otherwise, it treats `path_str` as a relative or absolute path and resolves it
      to an absolute path.
    - Normalizes path separators to forward slashes ("/").

    Args:
        path_str (str | None): The path string to expand. Can be None.

    Returns:
        str | None: The expanded and resolved absolute path as a string with forward
                    slashes, or None if the input was None or empty.
    """
    if not path_str: # Handle None or empty string input
        return None
    if path_str.startswith('~/'):
        # Expand "~/" to the user's home directory
        return str(pathlib.Path.home() / path_str[2:]).replace('\\', '/')
    # Resolve other paths (relative or absolute) to an absolute path
    return str(pathlib.Path(path_str).resolve()).replace('\\', '/')

# Main command group for Click.
# context_settings allows defining global help options.
@click.group(context_settings=dict(help_option_names=['-h', '--help']))
# --version option automatically generated by Click.
@click.version_option(version="0.10.4", prog_name="ghostmirror") 
# Definition of all command-line options.
# Each @click.option decorator defines a CLI flag or parameter.
# 'help' text is used for generating the --help output.
# 'default' provides default values if option is not specified.
# 'type' specifies the expected data type.
# 'multiple=True' allows an option to be specified multiple times (e.g., -c USA -c Canada).
# 'is_flag=True' defines boolean flags (present or not present).
@click.option('--arch', '-a', 'arch', type=str, default="x86_64", help="select arch, default 'x86_64'")
@click.option('--mirrorfile', '-m', 'mirrorfile', type=click.Path(exists=True, dir_okay=False, resolve_path=False), help="use mirror file instead of downloading mirrorlist")
@click.option('--country', '-c', 'country_filter', # Renamed to country_filter to match core.py config key
              type=str, multiple=True, help="select country from mirrorlist (can be used multiple times)")
@click.option('--country-list', '-C', 'country_list_flag', is_flag=True, help="show all possible countries")
@click.option('--uncommented', '-u', 'uncommented_only', # Renamed to uncommented_only
              is_flag=True, help="use only uncommented mirror")
@click.option('--downloads', '-d', 'downloads', type=int, default=4, show_default=True, help="set numbers of parallel download (currently not implemented)") # Clarified not implemented
@click.option('--timeout', '-O', 'timeout', type=int, default=8, show_default=True, help="set timeout in seconds for not reply mirror")
@click.option('--progress', '-p', 'progress', is_flag=True, help="show progress, default false")
@click.option('--progress-colors', '-P', 'progress_colors', is_flag=True, help="same -p but with colors for output table")
@click.option('--output', '-o', 'output_table', is_flag=True, help="enable table output")
@click.option('--speed', '-s', 'speed_test_mode', type=click.Choice(['light', 'normal', 'heavy', 'none'], case_sensitive=False), help="test speed for downloading pkg: light/normal/heavy/none") # Added 'none'
@click.option('--sort', '-S', 'sort_fields', type=str, multiple=True, help="sort result for any of fields, multiple fields supported (e.g., country,-speed,-stability_score)") # Example updated
@click.option('--list', '-l', 'list_output_file', type=str, help="create a file with list of mirrors, 'stdout' for output here")
@click.option('--max-list', '-L', 'max_list', # Renamed to max_list to match core.py config key
              type=int, help="set max numbers of output mirrors (default: unlimited)")
@click.option('--type', '-T', 'mirror_types', type=click.Choice(['http', 'https', 'all'], case_sensitive=False), default=['all'], multiple=True, show_default=True, help="select mirrors type: http, https, all")
# --investigate, --systemd, --time, --fixed-time are placeholders from original C version, not implemented in Python core.py
@click.option('--investigate', '-i', 'investigate_mode', type=click.Choice(['outofdate', 'error', 'all'], case_sensitive=False), multiple=True, help="investigate on mirror, mode: outofdate/error/all (currently not implemented)")
@click.option('--systemd', '-D', 'systemd_manage', is_flag=True, help="auto manager systemd.timer (currently not implemented)")
@click.option('--time', '-t', 'systemd_time', type=str, help="specific your preferred time in hh:mm:ss for systemd timer (currently not implemented)")
@click.option('--fixed-time', '-f', 'systemd_fixed_time', type=str, help="use fixed OnCalendar for systemd timer (currently not implemented)")
def main(**kwargs):
    """
    GhostMirror: A Python tool to rank Arch Linux pacman mirrors.

    This CLI allows users to fetch mirror lists, filter them by various criteria
    (country, protocol), test mirror speeds, compare package freshness, and
    generate ranked mirror lists for use with pacman.
    """
    # Create a configuration dictionary from all Click options
    config = {}
    for key, value in kwargs.items():
        config[key] = value

    # Process path-related options to expand and resolve them
    if config.get("mirrorfile"):
        config["mirrorfile"] = path_explode(config["mirrorfile"])

    if config.get("list_output_file") and config["list_output_file"].lower() != "stdout":
        config["list_output_file"] = path_explode(config["list_output_file"])

    # If progress_colors is true, progress should also be implicitly true
    if config.get("progress_colors"):
        config["progress"] = True
    
    # Rename CLI option names to match expected keys in core.py's config dict where necessary
    # This is done if 'param_name' in @click.option(...) differs from the desired config key.
    # Example: if @click.option had 'country_filters_cli' but core.py expects 'country_filter'
    # Here, most were aligned by changing the 'dest' (first string arg after flags) in @click.option.
    # For example, @click.option('--country', '-c', 'country_filter', ...) ensures kwargs['country_filter']
    # No explicit remapping needed here if dest names in @click.option match core.py's expectations.
    # I've already aligned 'country' to 'country_filter', 'uncommented' to 'uncommented_only',
    # and 'max_list_mirrors' to 'max_list' in the @click.option definitions.

    # Call the core processing function with the prepared configuration
    core.process_mirrors(config)

if __name__ == '__main__':
    main()
```
